[package]
name = "simularity_core_server"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import simularity_core_server`). If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "simularity_core_server"

# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use simularity_core_server;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]


[dependencies]
pyo3 = { version = "0.23.2", features = ["extension-module"] }
simularity-core = { path = "../core-rs" }

[features]
cuda = ["simularity-core/cuda"]
