[package]
name = "simularity-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.83"
encoding_rs = "0.8.34"
llama-cpp-2 = { path = "../llama-cpp-rs/llama-cpp-2", features = ["metal"] }
llama-cpp-sys-2 = { path = "../llama-cpp-rs/llama-cpp-sys-2", features = [
  "metal",
] }
serde = { version = "1.0.201", features = ["serde_derive"] }
